-- MySQL Script generated by MySQL Workbench
-- Thu Jan 10 03:02:03 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema simple-lms
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `simple-lms` ;

-- -----------------------------------------------------
-- Schema simple-lms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `simple-lms` DEFAULT CHARACTER SET utf8 ;
USE `simple-lms` ;

-- -----------------------------------------------------
-- Table `simple-lms`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simple-lms`.`User` ;

CREATE TABLE IF NOT EXISTS `simple-lms`.`User` (
  `UserId` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `Username` VARCHAR(12) NOT NULL,
  `PasswordHash` BINARY(64) NOT NULL,
  `PasswordSalt` BINARY(128) NOT NULL,
  `DateOfBirth` DATE NOT NULL,
  PRIMARY KEY (`UserId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simple-lms`.`Course`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simple-lms`.`Course` ;

CREATE TABLE IF NOT EXISTS `simple-lms`.`Course` (
  `CourseId` BIGINT(20) UNSIGNED NOT NULL,
  `CreditHours` SMALLINT(1) NOT NULL,
  `CourseName` VARCHAR(45) NOT NULL,
  `TeacherId` BIGINT(20) NOT NULL,
  PRIMARY KEY (`CourseId`),
  INDEX `TeacherFK_idx` (`TeacherId` ASC),
  UNIQUE INDEX `CourseId_UNIQUE` (`CourseId` ASC),
  CONSTRAINT `TeacherFK`
    FOREIGN KEY (`TeacherId`)
    REFERENCES `simple-lms`.`User` (`UserId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `simple-lms`.`Enrollment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `simple-lms`.`Enrollment` ;

CREATE TABLE IF NOT EXISTS `simple-lms`.`Enrollment` (
  `StudentId` BIGINT(20) NOT NULL,
  `CourseId` BIGINT(20) NOT NULL,
  `Grade` VARCHAR(2) NULL,
  PRIMARY KEY (`StudentId`, `CourseId`),
  INDEX `CourseFK_idx` (`CourseId` ASC),
  CONSTRAINT `CourseFK`
    FOREIGN KEY (`CourseId`)
    REFERENCES `simple-lms`.`Course` (`CourseId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `StudentFK`
    FOREIGN KEY (`StudentId`)
    REFERENCES `simple-lms`.`User` (`UserId`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
