-- MySQL Script generated by MySQL Workbench
-- Fri Jan 11 02:04:35 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mjosc-lms
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mjosc-lms
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mjosc-lms` DEFAULT CHARACTER SET utf8 ;
USE `mjosc-lms` ;

-- -----------------------------------------------------
-- Table `mjosc-lms`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mjosc-lms`.`Course` (
  `CourseId` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `CourseName` VARCHAR(45) NOT NULL,
  `CreditHours` SMALLINT(1) NOT NULL,
  `TeacherId` BIGINT(20) NOT NULL,
  PRIMARY KEY (`CourseId`),
  INDEX `TeacherId_idx` (`TeacherId` ASC),
  CONSTRAINT `TeacherId`
    FOREIGN KEY (`TeacherId`)
    REFERENCES `mjosc-lms`.`user` (`userid`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mjosc-lms`.`Enrollment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mjosc-lms`.`Enrollment` (
  `StudentId` BIGINT(20) NOT NULL,
  `CourseId` BIGINT(20) NOT NULL,
  `Grade` VARCHAR(2) NULL DEFAULT NULL,
  PRIMARY KEY (`StudentId`, `CourseId`),
  INDEX `CourseFK_idx` (`CourseId` ASC),
  CONSTRAINT `CourseFK`
    FOREIGN KEY (`CourseId`)
    REFERENCES `mjosc-lms`.`course` (`courseid`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `StudentFK`
    FOREIGN KEY (`StudentId`)
    REFERENCES `mjosc-lms`.`user` (`userid`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mjosc-lms`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mjosc-lms`.`User` (
  `UserId` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(45) NOT NULL,
  `LastName` VARCHAR(45) NOT NULL,
  `DateOfBirth` DATE NOT NULL,
  `Username` VARCHAR(12) NOT NULL,
  `PasswordHash` BINARY(64) NOT NULL,
  `PasswordSalt` BINARY(128) NOT NULL,
  `Role` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`UserId`))
ENGINE = InnoDB
AUTO_INCREMENT = 35
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
